### PR TITLE
Tests/add utils tests

### LINKED ISSUE #13: Missing unit tests for the `utils` module

### PR DESCRIPTION
**Pull request by saattrupdan**
Adding unit tests for the `utils` module.

Closes #13

### CODE REVIEW

**Comment by AJDERS** [comment]
test for `clear_memory`: 

```
class TestClearMemory:
    ob_count = gc.get_count()
    torch_mem = torch.cuda.memory_cached()
    clear_memory()
    assert gc.get_count() <= ob_count and torch.cuda.memory_cached() <= torch_mem
```

**Review by AJDERS — CHANGES_REQUESTED** [review]
I posted a test for `clear_memory`. Looks good to me besides that.

**Comment by saattrupdan** [comment]
@AJDERS Added your `clear_memory` test now, thanks!  👍

**Comment by saattrupdan** [comment]
@AJDERS Removed the CUDA cache test of the `clear_memory` function now, as I noticed it was always just 0, so the test didn't do anything. Kept the other part now, and made the inequality strict, to prevent trivialities. Ready for review now (assuming all tests pass).

**Review by AJDERS — APPROVED** [review]
LGTM!

**Pull request merged**
